# Jekyll
gems:
  - jekyll-redirect-from

# Custom
siteTitle: Diego Martins de Siqueira
siteDescription: Excellent developer who is passionate about creating things; 5 years of experience managing web applications, web projects and blogs.
avatar: img/avatar.jpg
background: img/background.jpg
description: Hey I'm Diego. Thanks for visiting my personal site!
resumeFile: https://dl.dropboxusercontent.com/u/3848960/corgi.pdf

icons:
  - icon: page-pdf
    link: resume.html
    title: Resume
  - icon: social-github
    link: http://www.github.com/DiSiqueira
    title: Github
  - icon: social-twitter
    link: https://twitter.com/DiSiqueira_
    title: Twitter
  - icon: social-facebook
    link: https://fb.com/DiSiqueira
  - icon: social-reddit
    link: https://www.reddit.com/r/diisiqueira
    title: Reddit

projects:
  - name: DSDownload
    link: https://github.com/DiSiqueira/DSDownload
  - name: TumblrDownloader
    link: https://github.com/DiSiqueira/TumblrDownloader
  - name: DSImgur
    link: https://github.com/DiSiqueira/DSImgur
